apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: neighbours
spec:
  version: {{ .TagName }}
  homepage: https://github.com/mosheavni/k8s-neighbours
  shortDescription: List pods on the same node as a given pod
  description: |
    Lists all pods scheduled on the same Kubernetes node as a given pod,
    or all pods running on a given node, across all namespaces.
  platforms:
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      {{ addURIAndSha "https://github.com/mosheavni/k8s-neighbours/releases/download/{{ .TagName }}/k8s-neighbours_linux_amd64.tar.gz" .TagName }}
      bin: kubectl-neighbours
    - selector:
        matchLabels:
          os: linux
          arch: arm64
      {{ addURIAndSha "https://github.com/mosheavni/k8s-neighbours/releases/download/{{ .TagName }}/k8s-neighbours_linux_arm64.tar.gz" .TagName }}
      bin: kubectl-neighbours
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      {{ addURIAndSha "https://github.com/mosheavni/k8s-neighbours/releases/download/{{ .TagName }}/k8s-neighbours_darwin_amd64.tar.gz" .TagName }}
      bin: kubectl-neighbours
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      {{ addURIAndSha "https://github.com/mosheavni/k8s-neighbours/releases/download/{{ .TagName }}/k8s-neighbours_darwin_arm64.tar.gz" .TagName }}
      bin: kubectl-neighbours
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      {{ addURIAndSha "https://github.com/mosheavni/k8s-neighbours/releases/download/{{ .TagName }}/k8s-neighbours_windows_amd64.zip" .TagName }}
      bin: kubectl-neighbours.exe
    - selector:
        matchLabels:
          os: windows
          arch: arm64
      {{ addURIAndSha "https://github.com/mosheavni/k8s-neighbours/releases/download/{{ .TagName }}/k8s-neighbours_windows_arm64.zip" .TagName }}
      bin: kubectl-neighbours.exe
