name: Create Release

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_call:
    inputs:
      release:
        description: "The type of semantic version change to apply to the release."
        required: true
        type: string
        default: "patch"

jobs:
  create-new-release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'linux/amd64, darwin/amd64, darwin/arm64'
            name: 'program'
            compress: 'false'
            dest: '.'

      - run: ls -la

      # - name: Get previous version
      #   id: previous-version
      #   run: echo "VALUE=$(cat VERSION)" >> $GITHUB_OUTPUT
      #
      # - name: Get next release version
      #   id: next-version
      #   run: |
      #     array=($(echo ${{ steps.previous-version.outputs.VALUE }} | tr . '\n'))
      #     target=2
      #     if [ ${{ inputs.release }} == "major" ]; then target=0; fi
      #     if [ ${{ inputs.release }} == "minor" ]; then target=1; fi
      #     array[$target]=$((array[$target]+1))
      #     if [ $target -lt 2 ]; then array[2]=0; fi
      #     if [ $target -lt 1 ]; then array[1]=0; fi
      #     output=$(IFS=. ; echo "${array[*]}")
      #     echo "VALUE=$output" >> $GITHUB_OUTPUT
      #
      # - name: Bump version
      #   run: |
      #     echo "${{ steps.next-version.outputs.VALUE }}" > VERSION
      #
      # - name: Generate version bump commit
      #   run: |
      #     git config user.name ${{ github.actor }}
      #     git config user.email '${{ github.actor }}@users.noreply.github.com'
      #     git commit -a -m "version bump ${{ steps.next-version.outputs.VALUE }}"
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #
      # - name: Create Pull Request
      #   id: cpr
      #   uses: peter-evans/create-pull-request@v4
      #   with:
      #     token: ${{ github.token }}
      #     title: "[skip ci] Release"
      #     branch: release
      #     delete-branch: true
      #     labels: release_auto_version_bump
      #
      # - name: Merge
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   run: |
      #     gh pr merge ${{ steps.cpr.outputs.pull-request-number }} --repo ${{ github.repository }} \
      #       --admin --delete-branch --body "Release ${{ steps.next-version.outputs.VALUE }}" -s
      #
      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: k8s-neighbours
      #     tag_name: ${{ steps.next-version.outputs.VALUE }}
      #     generate_release_notes: true
